[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.13.1",
    "aiohttp>=3.13.5",
    "asyncpg==0.30.0",
    "cryptography>=48.0.0",
    "fastapi==0.115.5",
    "python-dotenv==1.0.1",
    "sqlalchemy==2.0.36",
    "uvicorn==0.32.1",
]
